name: hybrid_search_engine

services:
  api:
    container_name: hybrid_search_engine_api
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - hybrid_search_engine_network

  redis:
    image: redis:alpine
    container_name: hybrid_search_engine_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - hybrid_search_engine_network
    volumes:
      - redis_data:/data

  postgres:
    image: pgvector/pgvector:pg16
    container_name: hybrid_search_engine_pgvector
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - hybrid_search_engine_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  hybrid_search_engine_network:
    driver: bridge

volumes:
  redis_data:
  postgres_data:
